######################################################################
# Automatically generated by qmake (1.07a) Wed Mar 16 18:39:57 2011
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += test.cpp
